name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: make library

  cuda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: make cuda

  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: make cli

  ebpf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src
      - uses: Swatinem/rust-cache@v2
      - run: cargo install bpf-linker --locked
      - run: make ebpf

  docker:
    name: Docker
    needs:
      - library
      - cli
      - cuda
      - ebpf

    if: >-
      github.event_name == 'push' &&
      github.ref_type == 'tag' &&
      startsWith(github.ref_name, 'v') &&
      contains(github.ref_name, '.')

    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/docker.yml
