name: Docker

on:
  workflow_call:

jobs:
  image:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        shell: bash
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
            | docker login ghcr.io \
                --username "${{ github.actor }}" \
                --password-stdin

      - name: Build image
        shell: bash
        run: |
          IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}"
          TAG="${GITHUB_REF_NAME}"

          docker buildx build \
            --platform linux/amd64 \
            --label "org.opencontainers.image.source=https://github.com/${GITHUB_REPOSITORY}" \
            --label "org.opencontainers.image.revision=${GITHUB_SHA}" \
            --label "org.opencontainers.image.version=${TAG}" \
            --tag "${IMAGE}:${TAG}" \
            --tag "${IMAGE}:latest" \
            --load \
            .

      - name: Push image
        shell: bash
        run: |
          IMAGE="ghcr.io/${GITHUB_REPOSITORY,,}"
          TAG="${GITHUB_REF_NAME}"

          docker push "${IMAGE}:${TAG}"
          docker push "${IMAGE}:latest"
